spring:
  application:
    name: building-limits-processor
  datasource:
    username: buildinglimits
    password: buildinglimitspassword
    url: jdbc:postgresql://localhost:5011/buildinglimits
  flyway:
    user: buildinglimits
    password: buildinglimitspassword
    url: jdbc:postgresql://localhost:5011/buildinglimits
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health
